export const DATA_TAGS = {
  complaint_rooms: 'complaint-rooms',
  complaint_room: 'complaint-room',
  client_complaint_rooms: 'client-complaint-rooms',
  clients: 'clients',
  client: 'client',
  products: 'products',
  active_products: 'active-products',
  inactive_products: 'inactive-products',
  chats: 'chats',
  open_chats: 'open-chats',
  closed_chats: 'closed-chats',
  orgs: 'orgs',
  org: 'org',
  users: 'users',
}